version: '3.5'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: internship-back
    ports:
      - ${PORT}:${PORT}
    restart: always
    env_file:
      - .env
    volumes:
      - 'D:\meduzzen\meduzzenn-iternship-back:/app'
      - /app/node_modules
    depends_on: [postgres-db]

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
      PGDATA: /data/postgres
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  node_modules:
