version: '3.5'
services:
  internship-back:
    build: .
    container_name: internship-back-cont
    volumes:
      - logs:/app/data
      - D:\meduzzen\meduzzenn-iternship-back:/app
      - modulse:/app/node_modules
    env_file: ./.env
    ports:
      - '3001:3001'
    restart: unless-stopped
    depends_on:
      - app-db
    networks:
      - localnetwork

  app-db:
    image: postgres
    container_name: internship-db-cont
    environment:
      - POSTGRES_PASSWORD=jktue2040s
      - POSTGRES_DB=nest-app-db
      - POSTGRES_USER=admin
    networks:
      - localnetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:8080
    environment:
      - ADMINER_DEFAULT_SERVER=internship-db-cont
    networks:
      - localnetwork
networks:
  localnetwork:
volumes:
  logs:
  modulse:
